### ISSUE TITLE
javascript error on CTRL+/

### ISSUE THREAD

**Issue by jdiercks** [jalehman/port#130]
Running Port 1.2.1 on Ubuntu 20.04 (and the problem was also present in Port 1.2.0).
When pressing the CTRL+/ shortcut, I get this error:

![image](https://user-images.githubusercontent.com/20462456/135482044-c26b73a6-a889-4e74-8a06-a83d12d65016.png)

**Comment by jdiercks** [comment]
... CTRL+TAB triggers the error too, regardless of whether Port has focus.

**Comment by arthyn** [comment]
Thanks, this should now be fixed in the latest release 1.3, let me know if you see it happen again.

**Comment by jdiercks** [comment]
Thanks, but still happening on 1.3:
![image](https://user-images.githubusercontent.com/20462456/136107444-aef20c5d-3ca1-462b-8828-9c0d6ffa13e8.png)

CTRL+/ :
![image](https://user-images.githubusercontent.com/20462456/136107617-65f06d5a-7b8e-47df-be3e-030ad45f9b58.png)

CTRL+TAB : 
![image](https://user-images.githubusercontent.com/20462456/136107701-8a7f1ee4-84d3-434f-9ba9-9b1f68c1b021.png)

**Comment by jdiercks** [comment]
Just updated to 1.4; same errors.

**Comment by arthyn** [comment]
@jdiercks hey can you confirm that you've recently restarted your computer or have closed all Port processes? The bug that caused this is basically old port processes still running trying to open the main window when it isn't there. So even though you've updated, the old processes still have the bug.

**Comment by jdiercks** [comment]
@arthyn Thanks, rebooting fixed it. I had assumed that `snap refresh port` would implicitly stop/restart processes, but I guess not.

Is there a recommended/clean way to stop/restart all port processes without rebooting? Obviously I could try something like `killall port` but that seems a little sledgehammery.

**Comment by arthyn** [comment]
@jdiercks  After the latest update it should do that automatically, there was a bug previously that made it look like it was closed but still had a background process running.

**Comment by jdiercks** [comment]
@arthyn Great, hanks! I think this issue can be closed then.
