### ISSUE TITLE
[bug] Comet creation doesnt work on windows

### ISSUE THREAD

**Issue by l3gacyb3ta** [jalehman/port#135]
**Bug Description*
When I try to make a comet on windows, it just gives me a blank error message immediately.

**To Reproduce**
Open Port
Click "Start without an id"
Give a name
click continue

**Expected Behavior**
A comet should be created

**Screenshots**
![image](https://user-images.githubusercontent.com/58434499/136244916-4a06c080-5fbb-48a9-85a2-0c0d869f1338.png)

**Environment:**
 - OS: Windows 11
 - Version: 21H2
 - Port Version: 1.4.0

**Comment by arthyn** [comment]
@l3gacyb3ta sorry about that, had an issue with the build. If you try again it should work now!

**Comment by sibwyl-batrep** [comment]
still doesn't work for me. I dunno whats wrong and how to fix that

**Comment by sibwyl-batrep** [comment]
@arthyn @l3gacyb3ta what can I do to change that

**Comment by arthyn** [comment]
@sibwyl-batrep are you seeing any errors? If the boot errored you should see a screen with the error, or if you're seeing something else you can click the bug in the right hand corner and two dev tools windows should popup, there might be errors there.

**Comment by sibwyl-batrep** [comment]
@l3gacyb3ta

**Comment by sibwyl-batrep** [comment]
@arthyn 
Booting Comet Failed
Last seen messages:
13:20:34 boot: found comet ~fabfen-pospub-pocsul-barset--hilmes-folweg-risweb-binzod
13:20:34 boot: retrieving latest block
13:20:35 boot: verifying keys
boot: if you're trying to start an L2 ship, upgrade your binary
13:20:35 boot: getting sponsor
13:20:35 boot: retrieving galaxy table

nothing else. debug shows nothing. I even updated to the latest version
